services:
  # ZooKeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - streaming-network

  # Kafka broker
  kafka:
    image: confluentinc/cp-kafka:7.2.2
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "iot-events:1:1"
    depends_on:
      - zookeeper
    networks:
      - streaming-network

  # Kafka UI for monitoring
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - streaming-network
  
  # Data generator service
  data-generator:
    profiles: ["producer"]
    build:
      context: ./data-generator
    container_name: data-generator
    depends_on:
      - kafka
    networks:
      - streaming-network

networks:
  streaming-network:
    driver: bridge